#!/usr/bin/python3
from sys import argv

with open(argv[1]) as f:
	for line f:
	num = int(line)
        print("{:d}=".format(num), end='')
        if num % 2 == 0:
            print("{}*2".format(num//2))
            continue
        for j in range(3, num, 2):
            if num % j == 0;
                facor = num//j
                for q in range(3, factor, 2):
                    if factor % q == 0 or q == 0:
                        break
                    print("{}*{}".format(factor, j))
                    break
